### ISSUE TITLE
dont split |

### ISSUE THREAD

**Issue by vagnerfonseca** [veg/hivtrace#38]
Hi Guys,
I have my sequences in this format, it identifies the clusters but does not separate by "|" for more detailed analysis of my sequences in json it is returning me "id": "1121_25_SEP_97_1997_732|37 |female|White|31|1997_732|HET|2" is there any order in the parameters?

>1121_25_SEP_97_1997_732|37|female|White|31|1997_732|HET|2

**Comment by spond** [comment]
Dear @vagnerfonseca,

I am not sure what you are asking about. Are you interested in parsing sequence headers to extract more information for network visualization? 

Best,
Sergei

**Comment by vagnerfonseca** [comment]
Dear @spond ,

Im sorry my English not good... 
**Are you interested in parsing sequence headers to extract more information for network visualization?**
Yes, but it not working.

**Comment by ArtPoon** [comment]
@spond, this repo's issue tracker should have some guidelines set on posting issues so that they  do not include potentially identifying information.  If this sequence label isn't artificial, then it potentially contains a person's gender, ethnicity, age, and date of sample collection or visit date, from which one might extrapolate birth year; and that person is presumably living with HIV.  Just to forestall others from posting even more detailed headers...

**Comment by spond** [comment]
Dear @vagnerfonseca,

An easier way to do annotate the network is to use the following script to inject attributes (attached)_ into an inferred JSON file. You can also change the `SEQUENCE_ID_FORMAT='plain'` statement in `hivtrace.py` script to use something supported by https://github.com/veg/hivclustering.

The inject script can read CSV/TSV/JSON files and add annotations to the network JSON file.

For example

```
python3 inject-attributes.py  -n network.json -t attributes.tsv -f "Field" "Field" "Number" 'x: float(x) if x != "None" else 0.' -o network-with-attribute.json
```

or 

```
 python3 inject-attributes.py  -n network.json -t attributes.tsv -f "gender" "Gender" "enum" '{"1" : "Male", "2" : "Female", "3" : "Trans F2M", "4" : "Trans M2F"}' -o network-with-attribute.json
```

The input file should be like this (first column is the node ID to match, other columns carry data attributed and can have whatever names you want)

```
ID Gender Year of Birth
my_id Male 1977
...
```

Best,
Sergei

[inject.zip](https://github.com/veg/hivtrace/files/1703520/inject.zip)

**Comment by nathanosman** [comment]
Hi @spond,

Thank you for sharing this script.
I have been trying to use it but I have had a "KeyError: 'Nodes'" at line 122, that I fixed by changing it from:
"for n in network_json ["Nodes"]:"
to:
"for n in network_json ['trace-results']["Nodes"]:" (which I deduced from the structure of the JSON object in the output of hivtrace.py).
I left the "SEQUENCE_ID_FORMAT='plain'" statement unchanged in the hivtrace.py script, is this why it didn't work? If so, would you mind giving more details about how to use other SEQUENCE_ID_FORMAT? I have read the README from hivclustering but I couldn't figure out the specifications of the AEH or LANL formatting to make it work.

When I load the JSON file injected with my attributes that I obtained with my modified version of inject-attributes.py on https://veg.github.io/hivtrace-viz/, I can search for specific attributes using the search box and the rims of the corresponding nodes start blinking (meaning that the injection worked, right?), but I would like to be able to use the Color drop-down list with my attributes, and I can't seem to make this work. I have tried renaming my own attributes with the same names as in the example loading by default, but it didn't work. The data in the "Attributes" tab seem not to be updated with the data from my own file either.
What do I need to be able to use these features?

Also (should I post this on the hivtrace-viz issues and not here?), the checkbox "Show small clusters" doesn't reset if previously checked when loading a new file to visualize, meaning that to show small clusters from the new file, the box has to be unchecked.

Thank you very much in advance.
Regards,
Nathan Osman

**Comment by spond** [comment]
Dear @nathanosman,

The `trace_results` key is only generated by the web version, while the standalone `hivnetworkcsv` does not wrap the results in this key. The injection script populates other fields in the JSON, and they will be misplaced if `trace_results` is present. Try the following fix:

[inject.zip](https://github.com/veg/hivtrace/files/1956505/inject.zip)

Best,
Sergei

PS Thanks for the tip about the buggy checkbox state persistence. Could you add that as a separate issue on the hivtrace-viz repo?

**Comment by nathanosman** [comment]
Dear @spond,

thank you for your quick answer.
The fix you provided works like a charm! I understand now why my (deceivingly not working) fix was not a real fix.
I actually generated the JSON file from `hivtrace` compiled and ran on my own computer, I don't know why the `trace_results` key is present in the file. The fix you provided works anyway so it is not an issue anymore.

Thank you again.
Regards,
Nathan

**Comment by nathanosman** [comment]
Dear @spond,

little update: some of my attributes don't show in the dropdowns, although they have been injected by the very same way other attributes that work have been injected.
Is there a particular reason why? Their names (that are the same as their labels) are "Cluster" and "CI", if that helps.

Regards,
Nathan

**Comment by spond** [comment]
Dear @nathanosman,

`hivtrace-viz` will not show categorical attributes with more than N values (N = 36 by default), because it is simply not feasible to show this many different colors that are easily distinguished by eye. See line 55 in https://github.com/veg/hivtrace-viz/blob/master/src/clusternetwork.js.

You can override this by defining more colors to use. One options is to edit the loop in 

```
_.each ([0,-0.5,0.5], function (k) {
    _.each (_networkCategoricalBase, function (s) {
        _networkCategorical.push (d3.rgb(s).darker (k).toString());
    });
});
```

to add more shades of base colors, like the following to add 24 more colors


```
_.each ([0,-0.5,-0.25,0.5,0.25], function (k) {
    _.each (_networkCategoricalBase, function (s) {
        _networkCategorical.push (d3.rgb(s).darker (k).toString());
    });
});
```

Best,
Sergei
