### ISSUE TITLE
subprocess.CalledProcessError: <exception str() failed>

### ISSUE THREAD

**Issue by Abrulion** [veg/hivtrace#60]
HIV-TRACE is failing for me as follows:

sudo hivtrace -i pruebatrace.FASTA -a resolve -r HXB2_prrt -t .015 -m 500 -g .05 -c 
Traceback (most recent call last):
  File "/usr/local/bin/hivtrace", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/hivtrace/hivtrace.py", line 840, in main
    attributes_file=ATTRIBUTES_FILE)
  File "/usr/local/lib/python3.5/dist-packages/hivtrace/hivtrace.py", line 729, in hivtrace
    complete_stderr)
subprocess.CalledProcessError: <exception str() failed>

Any ideas how can I solve this issue? 
Best
Rafael

**Comment by stevenweaver** [comment]
Dear @Abrulion, 

With each hivtrace run, a log file is produced (`hivtrace.log` by default). Would it be possible to email that log file to me so that I can be of better assistance?

My hunch is that the `tn93` binary is not being discovered, but the log will allow me to verify that conjecture.

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @liamxg, 

If you supply the `hivtrace.log` I can troubleshoot. Usually it's due to `tn93` missing. 

Best,
Steven
