### ISSUE TITLE
How to install hivtrace in windows10?

### ISSUE THREAD

**Issue by futureflsl** [veg/hivtrace#77]

**Comment by stevenweaver** [comment]
Dear @futureflsl, 

This might not be possible because it relies on `tn93`, which is only supported on Linux or macOS. I believe the most straightforward route on Windows would be to use Windows Subsystem. https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab

Best,
Steven

**Comment by futureflsl** [comment]
thanks,I hope this project will support windows system,wish it comming soon
